services:
  - type: web
    name: hand-sign-recognition
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: streamlit run streamlit-app.py --server.port=$PORT --server.address=0.0.0.0